# Generated by Django 2.1.5 on 2019-02-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SucculentApp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Title',
            field=models.CharField(default='Option A', max_length=50),
            preserve_default=False,
        ),
    ]
