# Generated by Django 2.1.5 on 2019-02-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SucculentApp', '0004_choice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ThreadId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SucculentApp.Thread'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='SenderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='PollId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SucculentApp.Poll'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='UserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
