# Generated by Django 2.1.5 on 2019-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SucculentApp', '0005_auto_20190203_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
