# Generated by Django 2.1.5 on 2019-04-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SucculentApp', '0006_auto_20190213_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='EndDate',
            field=models.DateField(null=True),
        ),
    ]
